### ISSUE TITLE
Calmitas Clone Heavily Glitched

### ISSUE THREAD

**Issue by chaapz** [DominicKarma/InfernumModePublic#108]
I'm simply going to list off the issues I've found fighting it; (this was in multiplayer)

No health bar, screen flickering, boss not where it seems to be, boss teleporting around glitchily, projectiles not being where they're supposed to be and teleporting around.

the issues mainly happened during the second phase, with the constructs.

edit: the boss also doesn't know when it dies, and simply disappears. Drops nothing.

**Comment by Habble53** [comment]
> I'm simply going to list off the issues I've found fighting it; (this was in multiplayer)
> 
> No health bar, screen flickering, boss not where it seems to be, boss teleporting around glitchily, projectiles not being where they're supposed to be and teleporting around.
> 
> the issues mainly happened during the second phase, with the constructs.
> 
> edit: the boss also doesn't know when it dies, and simply disappears. Drops nothing.

4- Any relevant media such as images or videos showcasing the issue, if applicable.
5- If the issue is an in-game bug, attach the client.log and server.log (if multiplayer).

These would help a lot. Having tested this recently I can only guess this is a mod conflict issue as we didn't have any problems with CalShadow in multiplayer.

**Comment by toasty599** [comment]
Logs.

**Comment by toasty599** [comment]
Reopen when you provide logs.
