### ISSUE TITLE
Abyss just ate the Archives... Dungeon & Abyss conflict

### ISSUE THREAD

**Issue by cuyx** [DominicKarma/InfernumModePublic#69]
Ain't gonna say something about that... Just being unlucky :/
![20230822133812_1](https://github.com/DominicKarma/InfernumModePublic/assets/142893705/6d369682-8cd9-4fff-b81f-9a19e01c4ab5)
![20230822134121_1](https://github.com/DominicKarma/InfernumModePublic/assets/142893705/98e694d8-e043-407c-bb74-5bf319083889)
![20230822134131_1](https://github.com/DominicKarma/InfernumModePublic/assets/142893705/a125c477-acd3-45c0-8ee1-eca6f2fe2097)

edit 1:54pm: I haven't said that Abyss also covers up most of a dungeon area because I can deal with it, but not the Acrhives. It makes playthrough unbeatable without cheats, like, damn bro 🤕

**Comment by cobaltw** [comment]
Also had a similar issue in my most recent world where some dungeon loot was unobtainable because the abyss erased it. It flooded most of the dungeon, too

**Comment by Raku-Shiratori** [comment]
Yeah I have to agree with this that it is an issue. Its happened to me in multiple worlds, its not a random thing it happens each time. The dungeon, half of it just gets outright deleted due to the Abyss overlapping onto it.

The only potential way I could see it being fixed is either lessening how far out the abyss goes or somehow being able to move the dungeon a good chunk more to towards spawn so it doesn't get overwritten.
But i am not a mod creator I am just a person here commenting on a bug report to let the dev know that this is a problem.

**Comment by toasty599** [comment]
Are these large or medium worlds.

**Comment by toasty599** [comment]
Should happen less often next patch, and hopefully not at all.

**Comment by Raku-Shiratori** [comment]
> 

For me its a large world. Havent tried Medium or small worlds yet, as I find large to be the more fun one.

**Comment by Mellohi138** [comment]
Increasing the clamping size unfortunately does not have an effect. The IL edit used to prevent the dungeon from spawning near the abyss used to work in 1.4.3, but after 1.4.4 it stopped taking effect. Which is weird because there aren't any crashes either. The code acts as if it doesn't exist at all.
